# Generated by Django 5.0 on 2024-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futboledos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseDeGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('equipo_primero_grupo_A', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_A', models.CharField(max_length=50)),
                ('equipo_primero_grupo_B', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_B', models.CharField(max_length=50)),
                ('equipo_primero_grupo_C', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_C', models.CharField(max_length=50)),
                ('equipo_primero_grupo_D', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_D', models.CharField(max_length=50)),
                ('equipo_primero_grupo_E', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_E', models.CharField(max_length=50)),
                ('equipo_primero_grupo_F', models.CharField(max_length=50)),
                ('equipo_segundo_grupo_F', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('note', models.TextField()),
                ('created_by', models.CharField(default='mcj', max_length=30)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
